Repository panelinhadees/server, pull requests merged in 2019-05, with the labels that each got.

#38 Creates first version of Schema
  package-lock.json
  package.json
  src/index.js
  src/model/githubDataFetcher.js
  src/model/githubQueries.js
  src/models/index.js
  src/resolvers/index.js
  src/schema/index.js
  src/schema/organization/OrganizationType.js
  src/schema/organization/members/OrganizationMemberType.js
  src/schema/organization/members/index.js
  src/schema/organization/members/resolvers.js
  src/schema/organization/queries.js
  src/schema/organization/repositories/RepositoryType.js
  src/schema/organization/repositories/index.js
  src/schema/organization/repositories/resolvers.js
  src/schema/organization/resolvers.js
  src/schema/organization/teams/TeamType.js
  src/schema/organization/teams/index.js
  src/schema/organization/teams/resolvers.js
  src/schema/user/UserType.js
  src/schema/user/queries.js
  src/schema/user/resolvers.js
Labels: enhancement

#72 Feat/47 add bio field
  src/github/queries.js
  src/schema/user/resolvers.js
  src/schema/user/types.js
Labels: enhancement

#106 Adds description for queries, types and fields on the schema
  src/schema/organization/contributors/queries.js
  src/schema/organization/contributors/types.js
  src/schema/organization/members/queries.js
  src/schema/organization/members/types.js
  src/schema/organization/queries.js
  src/schema/organization/repositories/queries.js
  src/schema/organization/repositories/types.js
  src/schema/organization/teams/queries.js
  src/schema/organization/teams/resolvers.js
  src/schema/organization/teams/types.js
  src/schema/organization/types.js
  src/schema/user/queries.js
  src/schema/user/types.js
Labels: docs

#110 Style/run lint
  .eslintrc.js
  package.json
  src/auth/route.js
  src/e2eHelpers/dataExtractor.js
  src/e2eHelpers/serverFactory.js
  src/github/dataFetcher.js
  src/github/queries.js
  src/github/restDataFetcher.js
  src/index.js
  src/schema/organization/__tests__/api.js
  src/schema/organization/__tests__/expectedResults.js
  src/schema/organization/__tests__/organization.spec.js
  src/schema/organization/contributors/__tests__/api.js
  src/schema/organization/contributors/__tests__/contributors.spec.js
  src/schema/organization/contributors/__tests__/expectedResults.js
  src/schema/organization/contributors/queries.js
  src/schema/organization/contributors/resolvers.js
  src/schema/organization/contributors/types.js
  src/schema/organization/members/__tests__/expectedResults.js
  src/schema/organization/members/__tests__/members.spec.js
  src/schema/organization/queries.js
  src/schema/organization/repositories/__tests__/api.js
  src/schema/organization/repositories/__tests__/expectedResults.js
  src/schema/organization/repositories/__tests__/repositories.spec.js
  src/schema/organization/repositories/types.js
  src/schema/organization/resolvers.js
  src/schema/organization/teams/__tests__/api.js
  src/schema/organization/teams/__tests__/expectedResults.js
  src/schema/organization/teams/__tests__/teams.spec.js
  src/schema/organization/types.js
  src/schema/user/__tests__/api.js
  src/schema/user/__tests__/expectedResults.js
  src/schema/user/__tests__/user.spec.js
  src/schema/user/resolvers.js
  src/schema/user/types.js
  src/testUtils/integration/dataExtractor.js
  src/utils/index.js
Labels: refactoring
