Repository panelinhadees/server, pull requests merged in 2019-04, with the labels that each got.

#22 Feat/10 apollo server base structure
  package-lock.json
  package.json
  src/index.js
  src/models/index.js
  src/resolvers/index.js
  src/schema/index.js
Labels: enhancement

#31 Adds intro to README.md
  README.md
Labels: docs, refactoring

#33 Refactor application GraphQL Schema
  package-lock.json
  src/index.js
  src/schema/index.js
Labels: refactoring
